security:

    encoders:
    # la manière dont mon mot de passe est haché
        AppBundle\Entity\User:  bcrypt

    providers:
    # où se trouvent mes users
        users:
            entity:
                class:    AppBundle\Entity\User
                property: username

    firewalls:
    # comment faut il se connecter pour accéder à telle ou telle section
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: users
            pattern:  "^/"
            form_login:
                check_path:  app_check_signin
                login_path:  app_signin
            logout:
                path: logout
                target: homepage

    access_control:
    # quelles permissions j'ai besoin pour accéder à une section
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/', roles: ROLE_USER }
